routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('/app/dashboard');
});

Route::get('/install', function () {
    echo \Artisan::call('migrate:fresh', ['--seed' => true]);

    echo \Artisan::call('view:clear');
    echo \Artisan::call('view:cache');
    echo \Artisan::call('storage:link');

    return 'installed';
});


Route::prefix('app')->name('app.')->middleware('auth')->group(function (){
    Route::view('dashboard', 'app.dashboard')->name('dashboard');
    Route::view('sms', 'app.sms')->name('sms');
    Route::view('settings', 'app.settings')->name('settings');
    Route::view('members', 'app.members')->name('members');


    Route::post('sms/purchase', [
        \App\Http\Controllers\SmsPurchaseController::class,
        'purchaseSms'
    ])->name('sms.purchase');

    Route::get('pay', [
        \App\Http\Controllers\DashboardController::class,
        'webhook'
    ])->name('webhook');


    Route::view('domain', 'app.domain')->name('domain');
    Route::view('enquiries', 'app.enquiries')->name('enquiries');


    Route::post('domain/purchase', [
        \App\Http\Controllers\DomainPurchaseController::class,
        'purchaseDomain'
    ])->name('domain.purchase');


    Route::get('logout', function(){
        auth()->logout();

        return back();
    });
});


Route::prefix('domain')->name('domain.')->middleware(['domain.validate'])->group(function (){

    Route::view('{member}', 'domains.member-page')->name('page');

});

Route::post('sms/webhook', [\App\Extensions\Sms\Drivers\TermiiSms::class,'webhook'])->name('sms.webhook');

app/Http/Livewire/BuySmsForm.php
<?php

namespace App\Http\Livewire;

use App\Models\Settings;
use Livewire\Component;
use Livewire\WithFileUploads;

class BuySmsForm extends Component
{
    use WithFileUploads;

    public $sms_rate;

    public $units;


    public $proof;

    protected $rules = [
        'proof' => 'required|file|max:1024',
    ];


    /**
     * @param $property
     * @throws \Illuminate\Validation\ValidationException
     */
    public function updated($property)
    {
        $this->validateOnly($property);
    }


    public function mount()
    {
        $this->fill([
            'sms_rate' => Settings::getSmsRate(),
            'units' => 1
        ]);
    }

    public function getCostProperty()
    {
        return $this->sms_rate * doubleval($this->units);
    }

    public function render()
    {
        return view('livewire.buy-sms-form');
    }
}

app/Http/Livewire/CurrentSubscription.php
<?php

namespace App\Http\Livewire;

use App\Models\User;
use Livewire\Component;

class CurrentSubscription extends Component
{
    public $currentSub;

    public function mount()
    {
        /** @var User $user */
        $user = request()->user();

        $this->fill([
            'currentSub' => $user->getCurrentSubscription()
        ]);

    }


    public function render()
    {
        return view('livewire.current-subscription');
    }
}

app/Http/Livewire/DomainSubscriptions.php
<?php

namespace App\Http\Livewire;

use App\Models\DomainSubscription;
use App\Models\User;
use Illuminate\Support\Facades\Storage;
use Livewire\Component;

class DomainSubscriptions extends Component
{

    public $subscriptions;


    public function mount()
    {
        /** @var User $user */
        $user = auth()->user();

        if($user->isMember()){
            $this->subscriptions = DomainSubscription::query()->where('user_id', $user->id)->get();
        } else {
            $this->subscriptions = DomainSubscription::all();
        }
    }


    public function downloadProof($path)
    {
        return Storage::download($path);
    }


    public function approve($subscription_id)
    {
        DomainSubscription::query()->where('id', $subscription_id)->update([
            'approved' => true,
            'expires_at' => now()->addYear()
        ]);

        $this->redirectRoute('app.domain');
    }


    public function render()
    {
        return view('livewire.domain-subscriptions');
    }
}

app/Http/Livewire/Domains/EnquiryForm.php
<?php

namespace App\Http\Livewire\Domains;

use App\Actions\MemberDomain\CreateEnquiry;
use App\Models\User;
use Livewire\Component;

class EnquiryForm extends Component
{

    public $username;

    public $product;

    public $name;
    public $phone;
    public $email;
    public $message;

    public $sent;

    protected $rules = [
        'name' => 'required|string',
        'phone' => 'required|numeric',
        'email' => 'required|string|email',
        'message' => 'required|string',
    ];

    /**
     * @param $propertyName
     * @throws \Illuminate\Validation\ValidationException
     */
    public function updated($propertyName)
    {
        $this->validateOnly($propertyName);
    }

    public function sendMessage()
    {
        $payload = $this->validate();

        $payload['product_name'] = $this->product->name;

        (new CreateEnquiry())->create($this->getMemberProperty(), $payload);

        $this->sent = true;

        $this->reset(['name', 'phone', 'email', 'message']);

    }

    public function mount($product)
    {
        $this->username = request('member');
        $this->product = $product;

    }

    /**
     * @return User|\Illuminate\Database\Eloquent\Builder|\Illuminate\Database\Eloquent\Model|object
     */
    public function getMemberProperty()
    {
        return User::query()->where('username', $this->username)->first();
    }

    public function render()
    {
        return view('livewire.domains.enquiry-form');
    }
}

app/Http/Livewire/EnquiryList.php
<?php

namespace App\Http\Livewire;

use App\Models\Enquiry;
use App\Models\User;
use Livewire\Component;

class EnquiryList extends Component
{
    protected $enquiries;

    public function mount()
    {


    }


    public function render()
    {
        /** @var User $user */
        $user = auth()->user();

        if($user->isMember()){
            $this->enquiries = Enquiry::query()->where('user_id', $user->id)->paginate(20);
        } else {
            $this->enquiries = Enquiry::query()->paginate(20);
        }

        return view('livewire.enquiry-list')
            ->with('enquiries', $this->enquiries);
    }
}

app/Http/Livewire/MemberList.php
<?php

namespace App\Http\Livewire;

use App\Enums\Roles;
use App\Models\User;
use Livewire\Component;
use Livewire\WithPagination;

class MemberList extends Component
{
    use WithPagination;

    protected $members;


    public function render()
    {
        $this->members = User::query()
            ->role(Roles::Member)
            ->paginate(10);

        return view('livewire.member-list')
            ->with('members', $this->members);
    }
}

app/Http/Livewire/MemberStatCard.php
<?php

namespace App\Http\Livewire;

use App\Enums\Roles;
use App\Models\User;
use Livewire\Component;

class MemberStatCard extends Component
{

    public $totalMembers;

    public $monthTotal;

    public function mount()
    {
        $this->fill([
            'totalMembers' => User::query()->role(Roles::Member)->count(),
            'monthTotal' => User::query()->whereMonth('created_at', date('m'))->role(Roles::Member)->count(),
        ]);
    }

    public function render()
    {
        return view('livewire.member-stat-card');
    }
}

app/Http/Livewire/MySmsBalance.php
<?php

namespace App\Http\Livewire;

use App\Models\SmsPurchase;
use App\Models\User;
use Livewire\Component;

class MySmsBalance extends Component
{

    public $balance;

    public $monthTotalPurchase;

    public function mount()
    {
        /** @var User $user */
        $user = auth()->user();

        $this->fill([
            'balance' => $user->getSmsBalance(),
            'monthTotalPurchase' => SmsPurchase::query()
                ->where('user_id', $user->id)
                ->where('approved', true)
                ->sum('units')
        ]);
    }


    public function render()
    {
        return view('livewire.my-sms-balance');
    }
}

app/Http/Livewire/ProductsListing.php
<?php

namespace App\Http\Livewire;

use App\Models\Website\Products;
use Illuminate\Support\Facades\Http;
use Livewire\Component;

class ProductsListing extends Component
{

    public $products;

    public function mount()
    {

        $this->fill([
            'products' => $this->getProducts()
        ]);

    }


    public function getProducts()
    {
        return Products::all();
    }


    public function render()
    {
        return view('livewire.products-listing');
    }
}

app/Http/Livewire/RenewDomainForm.php
<?php

namespace App\Http\Livewire;

use App\Models\Settings;
use Livewire\Component;
use Livewire\WithFileUploads;

class RenewDomainForm extends Component
{
    use WithFileUploads;

    public $domain_rate;

    public $proof;

    protected $rules = [
        'proof' => 'required|file|max:1024',
    ];


    /**
     * @param $property
     * @throws \Illuminate\Validation\ValidationException
     */
    public function updated($property)
    {
        $this->validateOnly($property);
    }


    public function mount()
    {
        $this->fill([
            'domain_rate' => Settings::getDomainRate(),
        ]);
    }


    public function render()
    {
        return view('livewire.renew-domain-form');
    }
}

app/Http/Livewire/Settings/DomainRateSetting.php
<?php

namespace App\Http\Livewire\Settings;

use App\Enums\SettingsEnum;
use App\Models\Settings;
use Livewire\Component;

class DomainRateSetting extends Component
{

    public $rate;

    public $saved;

    public function mount()
    {
        $this->fill([
            'rate' => Settings::getDomainRate(),
        ]);
    }

    public function updateRate()
    {
        Settings::saveSettings(SettingsEnum::DomainRatePerYear, $this->rate);

        $this->fill(['saved' => true]);
    }


    public function render()
    {
        return view('livewire.settings.domain-rate-setting');
    }
}

app/Http/Livewire/Settings/FeatureVideoUrlSetting.php
<?php

namespace App\Http\Livewire\Settings;

use App\Enums\SettingsEnum;
use App\Models\Settings;
use Livewire\Component;

class FeatureVideoUrlSetting extends Component
{

    public $setting;

    public $saved;

    public function mount()
    {
        $this->fill([
            'setting' => Settings::getVideoUrl(),
        ]);
    }

    public function updateSetting()
    {
        Settings::saveSettings(SettingsEnum::VideoUrl, $this->setting);

        $this->fill(['saved' => true]);
    }


    public function render()
    {
        return view('livewire.settings.feature-video-url-setting');
    }
}

app/Http/Livewire/Settings/MemberPageHeaderText.php
<?php

namespace App\Http\Livewire\Settings;

use App\Enums\SettingsEnum;
use App\Models\Settings;
use Livewire\Component;

class MemberPageHeaderText extends Component
{

    public $setting;

    public $saved;

    public function mount()
    {
        $this->fill([
            'setting' => Settings::getMemberPageHeaderText(),
        ]);
    }

    public function updateSetting()
    {
        Settings::saveSettings(SettingsEnum::MemberPageHeaderText, $this->setting);

        $this->fill(['saved' => true]);
    }


    public function render()
    {
        return view('livewire.settings.member-page-header-text');
    }
}

app/Http/Livewire/Settings/PhotoBgSetting.php
<?php

namespace App\Http\Livewire\Settings;

use App\Enums\SettingsEnum;
use App\Models\Settings;
use Illuminate\Support\Str;
use Livewire\Component;
use Livewire\WithFileUploads;

class PhotoBgSetting extends Component
{

    use WithFileUploads;

    public $photo;

    public $saved;

    public function updatedPhoto()
    {
        $this->validate([
            'photo' => 'image|max:1024',
        ]);
    }

    public function save()
    {
        if(!$this->photo) {
            $this->dispatchBrowserEvent('notification', [
               'type' => 'toast',
               'message' => 'No image was selected for upload!',
               'messageType' => 'error'
            ]);

            return ;
        }

        $path = $this->photo->storePublicly('public/bg');

        Settings::saveSettings(SettingsEnum::PhotoBg, Str::after($path, 'public/'));

        $this->fill(['saved' => true]);
    }


    public function render()
    {
        return view('livewire.settings.photo-bg-setting');
    }
}

app/Http/Livewire/Settings/SmsRateSetting.php
<?php

namespace App\Http\Livewire\Settings;

use App\Enums\SettingsEnum;
use App\Models\Settings;
use Livewire\Component;

class SmsRateSetting extends Component
{

    public $rate;

    public $saved;

    public function mount()
    {
        $this->fill([
            'rate' => Settings::getSmsRate(),
        ]);
    }

    public function updateRate()
    {
        Settings::saveSettings(SettingsEnum::SmsRate, $this->rate);

        $this->fill(['saved' => true]);
    }

    public function render()
    {
        return view('livewire.settings.sms-rate-setting');
    }
}

app/Http/Livewire/Settings/UserProfileSettingsForm.php
<?php

namespace App\Http\Livewire\Settings;

use App\Models\User;
use Livewire\Component;

class UserProfileSettingsForm extends Component
{

    /** @var User */
    public $user;

    protected $rules = [
        'user.name' => 'required|string',
        'user.phone' => 'required|numeric',
        'user.email' => 'required|string|email',
//        'user.username' => 'required|string|min:4',
    ];

    public function mount()
    {
        $this->fill([
            'user' => auth()->user()
        ]);
    }


    public function updateProfile()
    {
        $payload = $this->validate()['user'];


        $this->dispatchBrowserEvent('notification', [
            'type' => 'loading',
            'message' => 'Updating profile'
        ]);

        $this->user->fill($payload);

        $this->user->save();


        $this->dispatchBrowserEvent('notification', [
            'type' => 'toast',
            'message' => 'Profile updated!',
            'messageType' => 'success'
        ]);

    }

    public function render()
    {
        return view('livewire.settings.user-profile-settings-form');
    }
}

app/Http/Livewire/SmsBalanceCard.php
<?php

namespace App\Http\Livewire;

use App\Extensions\Sms\TextMessaging;
use App\Models\SmsPurchase;
use Livewire\Component;

class SmsBalanceCard extends Component
{

    public $balance;

    public $monthTotalPurchase;

    public function mount()
    {
        $this->fill([
            'balance' => TextMessaging::getSmsUnitBalance(),
            'monthTotalPurchase' => SmsPurchase::query()->where('approved', true)->sum('units')
        ]);
    }

    public function render()
    {
        return view('livewire.sms-balance-card');
    }
}

app/Http/Livewire/SmsPurchaseList.php
<?php

namespace App\Http\Livewire;

use App\Models\SmsPurchase;
use App\Models\User;
use Illuminate\Support\Facades\Storage;
use Livewire\Component;

class SmsPurchaseList extends Component
{

    public $sms_purchases;


    public function mount()
    {
        /** @var User $user */
        $user = auth()->user();

        if($user->isMember()){
            $this->sms_purchases = SmsPurchase::query()->where('user_id', $user->id)->get();
        } else {
            $this->sms_purchases = SmsPurchase::all();
        }
    }


    public function downloadProof($path)
    {
        return Storage::download($path);
    }


    public function approve($id)
    {
        /** @var SmsPurchase $sms_purchase */
        $sms_purchase = SmsPurchase::query()->where('id', $id)->first();

        $sms_purchase->update([
            'approved' => true,
        ]);

        /** @var User $member */
        $member = $sms_purchase->user;
        $member->creditSmsUnit($sms_purchase->units);

        $this->redirectRoute('app.sms');
    }


    public function render()
    {
        return view('livewire.sms-purchase-list');
    }
}

app/Http/Livewire/SmsUsageList.php
<?php

namespace App\Http\Livewire;

use App\Models\SmsUsage;
use App\Models\User;
use Livewire\Component;

class SmsUsageList extends Component
{
    public $sms_usages;


    public function mount()
    {
        /** @var User $user */
        $user = auth()->user();

        if($user->isMember()){
            $this->sms_usages = SmsUsage::query()->where('user_id', $user->id)->get();
        } else {
            $this->sms_usages = SmsUsage::all();
        }
    }


    public function render()
    {
        return view('livewire.sms-usage-list');
    }
}

app/Http/Livewire/Utils/Alert.php
<?php

namespace App\Http\Livewire\Utils;

use Livewire\Component;

class Alert extends Component
{

    protected $listeners = [
        'alert' => 'alert'
    ];

    public $show;

    public function mount()
    {
        $this->fill([
            'show' => false,
        ]);
    }

    public function alert()
    {
        $this->show = true;
    }

    public function render()
    {
        return view('livewire.utils.alert');
    }
}

resources/views/livewire/buy-sms-form.blade.php
<div>
    <form method="post" action="{{ route('app.sms.purchase') }}" enctype="multipart/form-data">
        @csrf
        <div class="flex flex-col pt-4">
            <label for="" class="text-lg">Units</label>
            <input type="number" id="unit" name="units" wire:model="units"
                class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 mt-1
                   leading-tight focus:outline-none focus:shadow-outline">
            <span>
                Cost: NGN{{ number_format($this->cost, 2) }}

                <input type="hidden" id="amount" value="{{ $this->cost * 100 }}" name="amount" />

            </span>
        </div>

        {{-- <h2 class="pt-2">Pay NGN{{ number_format($this->cost, 2) }} into this account below </h2> --}}
        <div class="flex flex-col pt-2">

            <!-- Tabs -->
            <ul id="tabs" class="inline-flex pt-2 px-1 w-full border-2">
                <li class="px-4 text-white-800  m-3 font-semibold p-3 rounded-t border-2"><a
                        id="default-tab" href="#first"> Online Payment </a></li>
                <li class="px-4 text-white-800  m-3 font-semibold p-3 rounded-t border-2"><a href="#second">Bank Transfer </a></li>
            </ul>

            <!-- Tab Contents -->
            <div id="tab-contents">
                <div id="first" class="p-4">


                    <div onclick="payWithPaystack()"
                        class="bg-green-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded-full">
                        Pay with Paystack
                    </div>


                </div>
                <div id="second" class="hidden p-4">

                    <hr>
                    <label for="" class="text-lg">ACCOUNT NAME :<strong> BNIT CONSULT LIMITED</strong></label>
                    <label for="" class="text-lg">ACCOUNT NUMBER: <strong>0643860619 </strong></label>
                    <label for="" class="text-lg">BANK NAME: <strong> Trust Bank</strong></label>
                    <hr>

                    <label for="" class="text-lg pt-4">Upload Proof Payment (image, pdf)</label>
                    <input type="file" name="proof" wire:model="proof" accept="application/pdf, image/*"
                        class="shadow appearance-none border rounded w-full py-2 px-3
                   text-gray-700 mt-1 leading-tight focus:outline-none focus:shadow-outline">
                    @error('proof')
                        <span class="text-red-500">{{ $message }}</span>
                    @enderror


                </div>
            </div>


        </div>

        <div class="flex flex-col pt-4">


        </div>

        <!--Footer-->
        <div class="flex justify-end pt-2">
            <button id="domainBtn" class="px-4 bg-indigo-500 py-1 rounded-lg text-gray-100 hover:bg-indigo-400 hover:text-white mr-2">
                Submit
            </button>
        </div>

    </form>
</div>

@push('scripts')
    <script src="https://js.paystack.co/v1/inline.js"></script>

    <script>
        // function payWithPaystack() {

        // }
        //const paymentForm = document.getElementById('paymentForm');
        //paymentForm.addEventListener("submit", payWithPaystack, false);
        function payWithPaystack() {
            //e.preventDefault();
            var amount = parseInt(document.getElementById("amount").value);
            let handler = PaystackPop.setup({
                key: 'pk_live_036013ff9241213fc1ace2504181d9a1981ea791', // Replace with your public key
                email: "{{ auth()->user()->email }}",
                label: "For " + document.getElementById("unit").value + ' units',
                amount: amount+100,
                metadata: {
                    'paymentFor': 'sms',
                    'email': '{{ auth()->user()->email }}',
                    'unit': document.getElementById("unit").value
                },
                ref: '' + Math.floor((Math.random() * 1000000000) +
                1), // generates a pseudo-unique reference. Please replace with a reference you generated. Or remove the line entirely so our API will generate one for you
                // label: "Optional string that replaces customer email"
                onClose: function() {
                    alert('Window closed.');
                },
                callback: function(response) {
                    let message = 'Payment complete! Reference: ' + response.reference;
                    // alert(message);
                    window.location = response.redirecturl;

                    console.log(response);
                }
            });
            handler.openIframe();
        }
    </script>
@endpush

resources/views/livewire/current-subscription.blade.php
@php

/** @var \App\Models\DomainSubscription $currentSub */
/** @var \App\Models\User $user */

$user = request()->user();

$domain_url = route('domain.page', ['member' => $user->username]);

@endphp

<div class="w-full lg:w-6/12 xl:w-3/12 px-4">
    <div class="relative flex flex-col min-w-0 break-words bg-white rounded mb-6 xl:mb-0 shadow-lg">
        <div class="flex-auto p-4">
            <div class="flex flex-wrap">
                <div class="relative w-full pr-4 max-w-full flex-grow flex-1">
                    <h5 class="text-gray-500 uppercase font-bold text-xs">
                        Current Subscription
                    </h5>
                    <span class="font-semibold text-xl text-gray-800">
                        @if($currentSub)
                            Expires: <br>{{$currentSub->expires_at->format('jS M, Y')}}
                        @else
                            No active subscription
                            <br>
                            <a class="bg-indigo-500 modal-open text-white active:bg-indigo-600 text-xs font-bold uppercase px-3 py-1 rounded outline-none focus:outline-none mr-1 mb-1"
                               href="{{route('app.domain')}}">
                            Subscribe
                        </a>
                        @endif
                    </span>
                    @if($currentSub)

                        <hr class="my-3">

                        <div>
                            <label for="price" class="block text-sm leading-5 font-medium text-gray-700">
                                Domain Link:
                            </label>
                            <div class="mt-1 relative rounded-md shadow-sm">
                                <input class="form-input block w-full pl-7 pr-12 sm:text-sm sm:leading-5 text-gray-400"
                                       value="{{$domain_url}}">
                                <div class="absolute inset-y-0 right-0 flex items-center">
                                    <button class=" h-full py-0 pl-2 pr-3 border-transparent bg-transparent font-bold
                                    text-blue-600 sm:text-sm sm:leading-5" id="copy">
                                        copy
                                    </button>
                                </div>
                            </div>
                        </div>



                    @endif
                </div>

            </div>

        </div>
    </div>
</div>

@push('scripts')

<script>
    $('#copy').click(function(){
        var $temp = $("<input>");
        $("body").append($temp);
        $temp.val('{{$domain_url}}').select();
        document.execCommand("copy");
        $temp.remove();
        window.System.toast('copied!', 'success');
    });
</script>

@endpush

resources/views/livewire/member-stat-card.blade.php
<div class="w-full lg:w-6/12 xl:w-3/12 px-4">
    <div class="relative flex flex-col min-w-0 break-words bg-white rounded mb-6 xl:mb-0 shadow-lg">
        <div class="flex-auto p-4">
            <div class="flex flex-wrap">
                <div class="relative w-full pr-4 max-w-full flex-grow flex-1">
                    <h5 class="text-gray-500 uppercase font-bold text-xs">
                        Members
                    </h5>
                    <span class="font-semibold text-xl text-gray-800">
                        {{number_format($totalMembers)}}
                    </span>
                </div>
                <div class="relative w-auto pl-4 flex-initial">
                    <div class="text-white p-3 text-center inline-flex items-center justify-center w-12 h-12 shadow-lg rounded-full bg-red-500">
                        <i class="fas fa-users"></i>
                    </div>
                </div>
            </div>
            <p class="text-sm text-gray-500 mt-4">
                <span class="text-green-500 mr-2">
                  <i class="fas fa-coins"></i> {{$monthTotal}}
                </span>
                <span class="whitespace-no-wrap">
                  This month
                </span>
            </p>
        </div>
    </div>
</div>

resources/views/livewire/my-sms-balance.blade.php
<div class="w-full lg:w-6/12 xl:w-3/12 px-4">
    <div class="relative flex flex-col min-w-0 break-words bg-white rounded mb-6 xl:mb-0 shadow-lg">
        <div class="flex-auto p-4">
            <div class="flex flex-wrap">
                <div class="relative w-full pr-4 max-w-full flex-grow flex-1">
                    <h5 class="text-gray-500 uppercase font-bold text-xs">
                        SMS Units Balance
                    </h5>
                    <span class="font-semibold text-xl text-gray-800">
                        {{number_format($balance)}}
                    </span>
                </div>
                <div class="relative w-auto pl-4 flex-initial">
                    <div class="text-white p-3 text-center inline-flex items-center justify-center w-12 h-12 shadow-lg rounded-full bg-red-500">
                        <i class="fas fa-users"></i>
                    </div>
                </div>
            </div>
            <p class="text-sm text-gray-500 mt-4">
                <span class="text-green-500 mr-2">
                  <i class="fas fa-coins"></i> {{$monthTotalPurchase}}
                </span>
                <span class="whitespace-no-wrap">
                  Purchases this month
                </span>
            </p>
        </div>
    </div>
</div>

resources/views/livewire/renew-domain-form.blade.php
<div>
    <form method="post" action="{{route('app.domain.purchase')}}"
          enctype="multipart/form-data">
        @csrf
        <div class="flex flex-col pt-4">
            <input type="hidden" id="amount" name="amount" value="{{$domain_rate}}">
            <span>
                Cost: NGN{{ number_format($domain_rate, 2) }}
            </span>
        </div>

        <div class="flex flex-col pt-4">

            <!-- Tabs -->
            <ul id="tabs" class="inline-flex pt-2 px-1 w-full border-2">
                <li class="px-4 text-white-800  m-3 font-semibold p-3 rounded-t border-2"><a
                        id="default-tab" href="#first"> Online Payment </a></li>
                <li class="px-4 text-white-800  m-3 font-semibold p-3 rounded-t border-2"><a href="#second">Bank Transfer </a></li>
            </ul>

            <!-- Tab Contents -->
            <div id="tab-contents">
                <div id="first" class="p-4">


                    <div onclick="payWithPaystack()"
                        class="bg-green-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded-full">
                        Pay with Paystack
                    </div>


                </div>
                <div id="second" class="hidden p-4">

                    <hr>
                    <label for="" class="text-lg">ACCOUNT NAME :<strong> BNIT CONSULT LIMITED</strong></label>
                    <label for="" class="text-lg">ACCOUNT NUMBER: <strong>0643860619 </strong></label>
                    <label for="" class="text-lg">BANK NAME: <strong> Trust Bank</strong></label>
                    <hr>

                    <label for="" class="text-lg pt-4">Upload Proof Payment (image, pdf)</label>
                    <input type="file" name="proof" wire:model="proof" accept="application/pdf, image/*"
                    class="shadow appearance-none border rounded w-full py-2 px-3
                    text-gray-700 mt-1 leading-tight focus:outline-none focus:shadow-outline">
             @error('proof') <span class="text-red-500">{{ $message }}</span> @enderror



                </div>
            </div>
        </div>

        <!--Footer-->
        <div class="flex justify-end pt-2">
            <button id="domainBtn" class="px-4 bg-indigo-500 py-1 rounded-lg text-gray-100 hover:bg-indigo-400 hover:text-white mr-2">
                Submit
            </button>
        </div>

    </form>
</div>


@push('scripts')
    <script src="https://js.paystack.co/v1/inline.js"></script>

    <script>
        // function payWithPaystack() {

        // }
        //const paymentForm = document.getElementById('paymentForm');
        //paymentForm.addEventListener("submit", payWithPaystack, false);
        function payWithPaystack() {
            //e.preventDefault();
            let handler = PaystackPop.setup({
                key: 'pk_live_036013ff9241213fc1ace2504181d9a1981ea791', // Replace with your public key
                email: "{{ auth()->user()->email }}",
                label: "For Domain",
                amount: document.getElementById("amount").value,
                metadata: {
                    'paymentFor': 'domain',
                    'email': '{{ auth()->user()->email }}',
                },
                ref: '' + Math.floor((Math.random() * 1000000000) +
                1), // generates a pseudo-unique reference. Please replace with a reference you generated. Or remove the line entirely so our API will generate one for you
                // label: "Optional string that replaces customer email"
                onClose: function() {
                    alert('Window closed.');
                },
                callback: function(response) {
                    let message = 'Payment complete! Reference: ' + response.reference;
                    // alert(message);
                    window.location = response.redirecturl;

                    console.log(response);
                }
            });
            handler.openIframe();
        }
    </script>
@endpush